verbose: false
instrumentation:
    root: .
    default-excludes: true
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
hooks:
    hook-run-in-context: true
    post-require-hook: null
